### ISSUE TITLE
Why do we still need to download the dataset ourselves?

### ISSUE THREAD

**Issue by laplace666666** [jdkim6413/Tutorial-for-Time-Series-Prediction#1]
Why do we still need to download the dataset ourselves?

**Comment by jdkim6413** [comment]
This repository is for my publication "Tutorial on time series prediction using 1D-CNN and BiLSTM: A case example of peak electricity demand and system marginal price prediction".
https://www.sciencedirect.com/science/article/abs/pii/S0952197623010011?via%3Dihub

Some of data can be automatically acquired by official API of crawling but some of data is not able to collect like as we expected. That's why I showed several methods to collect and use dataset as a tutorial in my article. I hope this answer can help you!
